### ISSUE TITLE
Bug: Template resolution deletes two characters

### ISSUE THREAD

**Issue by jbnv** [dvargas92495/roamjs-com#738]
Sorry if this has already been posted. When RoamJS resolves a template, it deletes the two characters before the trigger (`jj` &c). So the string `abcdjjtoday` becomes `ab[[October 6th, 2021]]` instead of `abcd[[October 6th, 2021]]`.

**Comment by jbnv** [comment]
SmartBlocks extension.

**Comment by jbnv** [comment]
Hmm. I know I changed my trigger configuration in roam/js/smartblocks from `xx` to `jj` and somehow it was reset to `xx`.  I removed the old RoamJS code and installed Marketplace, so I shouldn't have v1 left in my graph.

I'm not set up on Loom and I don't want to install software on my machine for just one use. I stated the observed behavior in plain language so I'm not sure how a video of the same thing will add any info.

**Comment by dvargas92495** [comment]
I typically ask for videos as there are details that users aren't aware of enough to say in plain text that is caught on video that could illuminate a bug. Either that, or will need more context/repro steps otherwise I can't debug what's going on

I get the sense still that this might be a v1 bug and not a v2 bug. Here's me running v2, notice that "today" is not entered into the input:

![sb2](https://user-images.githubusercontent.com/7143571/136494473-ba81ba23-57a4-4f2e-b0c3-37d903e88931.gif)

Here' me running in v1. The today typing in the input, while not showing the bug here, could sometimes cause inconsistent text clearing bc it's done manually

![sb3](https://user-images.githubusercontent.com/7143571/136495871-837782a2-f71d-40e0-8914-dcfe2bf2045c.gif)

**Comment by jbnv** [comment]
The latter behavior is what I'm seeing. I'll see if I can find where the v1 code is still running in my graph.
